### ISSUE TITLE
estos métodos (habrá más) son `const`

### ISSUE THREAD

**Issue by cleongh** [UCM-FDI-DISIA/NineandoCorp#36]
https://github.com/UCM-FDI-DISIA/NineandoCorp/blob/56a4d0cf62846ac442ca4428a4c6b071fb35c187/ProyectoH/src/systems/EnemySystem.h#L38

**Comment by nico-best1** [comment]
He hecho un repaso para buscar los que no tenian const en todo el proyecto, puede que se me haya pasado alguno, si os encontrais alguno cambiadlo
