### ISSUE TITLE
mejor objetos para botones ("towernormalbutton")

### ISSUE THREAD

**Issue by cleongh** [UCM-FDI-DISIA/NineandoCorp#39]
https://github.com/UCM-FDI-DISIA/NineandoCorp/blob/56a4d0cf62846ac442ca4428a4c6b071fb35c187/ProyectoH/src/systems/HUDSystem.h#L86

**Comment by Marc0sPM** [comment]
No entiendo muy bien a que te refieres

**Comment by Marc0sPM** [comment]
Nuevo struct TowerButton que contiene la entidad del button, de la imagen y la posición inicial.
