### ISSUE TITLE
en el .h para que se pueda inlinear

### ISSUE THREAD

**Issue by cleongh** [UCM-FDI-DISIA/NineandoCorp#45]
https://github.com/UCM-FDI-DISIA/NineandoCorp/blob/56a4d0cf62846ac442ca4428a4c6b071fb35c187/ProyectoH/src/components/AttackComponent.cpp#L50

**Comment by nico-best1** [comment]
Como con los const de los metodos get he hecho un repaso por el codigo, si se me ha pasado alguno cambiadlo
